version: '3'

services:
  fastapi:
    build: web-app/backend/
    restart: always
    ports: 
      - 8080:8080
    container_name: fastapi

  streamlit:
    build: web-app/frontend/
    restart: always
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    container_name: streamlit